name: Build the app and package JAR
run-name: >
  ${{ startsWith(github.ref, 'refs/tags/v') &&
  format('Release {0}', github.ref_name) ||
  format('Build for commit "{0}"', github.event.head_commit.message) }}
  by ${{ github.actor }}
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Build the app
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          architecture: 'x64'
      - name: Build the app
        run: mvn
      - name: Zip up the javadoc
        run: cd target/site && zip -r javadoc.zip apidocs && cd -
      - name: Create a release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: target/*.jar target/site/javadoc.zip
